version: '3.8'

services:
  home-library-app:
    container_name: home-library
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    restart: always
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public"
    depends_on:
      - postgres-db
    volumes:
      - ./src:/app/src
    networks:
      - home-library

  postgres-db:
    container_name: postgres-db
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command:
      ['postgres', '-c', 'logging_collector=on', '-c', 'log_statement=all']
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - home-library

networks:
  home-library:
    driver: bridge

volumes:
  postgres-data:
